# Task and Workflow states
CLAIMED = 'CLAIMED'
FAILED = 'FAILED'
PAUSED = 'PAUSED'
PENDING = 'PENDING'
SUCCESS = 'SUCCESS'
IGNORE = 'IGNORE'
RUNNING = 'RUNNING'

# Task Def states (state of docker image)
BUILDING = 'BUILDING'
BUILDFAILED = 'BUILD FAILED'
BUILDPENDING = 'BUILD PENDING'
READY = 'READY'
